# Site settings
title: Stages Locations
email: c.pereirabarra1@uni.brighton.ac.uk
description: The locations of stages around the festival.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://carolinebarra.github.io/" # the base hostname & protocol for your site
copyright: '&copy; 2021 Csaba Toth'


# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: red-indigo

# Android AR Map app
application_name: Recycling Trashcan ARMap
app_source_repo: "https://github.com/carolinebarra/Stages-Location"
app_issues: https://github.com/RecyclingTrashCans/recycling-trashcan-armap/issues/
play_store_url: https://play.google.com/store/apps/details?id=dev.csaba.armap.recyclingtrashcans

# Google Analytics account ID (UA-XXXXXXXX-X)
#google-analytics-ua: UA-86563829-9
#gmaps_yo: "AIzaSyBm7DK2d-zrF1zOOEyDpoMyLiUWwrAROuk"
#main_map:
 # lat: 36.814079
  #lon: -119.7442877
